### PR TITLE
update

### PR DESCRIPTION
**Pull request by yerlirock**

### CODE REVIEW

**Comment by ghost** [comment]
**# What the hell!**
You can't add this things to official CyanogenMod.

**Comment by yerlirock** [comment]
i am sorry i dont know what i am done  

```
12 Haziran 2016 18:19 Pazar tarihinde Trafalgar-Square <notifications@github.com> şöyle yazdı:
```

 # What the hell!
You can't add this things to official CyanogenMod.—

**Comment by yerlirock** [comment]
how can i fix it :( 

```
12 Haziran 2016 18:19 Pazar tarihinde Trafalgar-Square <notifications@github.com> şöyle yazdı:
```

 # What the hell!
You can't add this things to official CyanogenMod.—

**Comment by ghost** [comment]
Nothing happened.
Nothing to fix.

**Comment by yerlirock** [comment]
i am realy realy sorry :(( 

```
12 Haziran 2016 18:48 Pazar tarihinde Trafalgar-Square <notifications@github.com> şöyle yazdı:
```

 Nothing happened.
Nothing to fix.—

**Pull request closed without merging**
